### PR TITLE
TST: bump artifact@v3->v4

### PR DESCRIPTION
**Pull request by tangkong**
## Description
Bump artifact@v3->v4

## Motivation and Context
V3 is being deprecated

## How Has This Been Tested?
CI?

## Where Has This Been Documented?
This PR

### CODE REVIEW

**Review by ZLLentz — DISMISSED** [review]
CI issues unrelated

**Comment by tangkong** [comment]
whoops got knee deep in the gha workflows before seeing your review.  Did these ever pass?  Do we care?  Maybe if I don't sort it out with this we just forge ahead

**Comment by ZLLentz** [comment]
If the failures are unrelated to this PR, we should merge and forge ahead

**Comment by tangkong** [comment]
I'm willing to bet these are unrelated to the actions version bumps.  I'll re-request review and move on

**Review by ZLLentz — APPROVED** [review]
I think they are unrelated too

**Pull request merged**
